apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "192.168.28.90:6443"
networking:
    podSubnet: "172.18.0.0/16"
etcd:
    external:
        endpoints:
        - https://192.168.28.90:2379
        - https://192.168.28.91:2379
        - https://192.168.28.92:2379
        caFile: /etc/kubernetes/pki/etcd/ca.crt
        certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
        keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
